name: FPL Daily Data

on:
  schedule:
    - cron: "0 1 * * *"  # runs 01:00 UTC (06:30 IST) daily
  workflow_dispatch: {}   # lets you run it manually too

permissions:
  contents: write

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Fetch live FPL data
        run: |
          python fpl_dump.py --out ./data

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            TS=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
            git commit -m "FPL data refresh: ${TS}"
            git push
          fi